Task/gec 25/shared dialog component
bert-bae/geckos pull request #9
Opened 2020-12-28 00:29 UTC by bert-bae

2020-12-31 21:41 UTC, arromeo requested changes
I'm thinking this Storybook directory should be in the .gitignore? I thought I had setup and deleted all of the Storybook boilerplate. Was this generated by something?

2020-12-31 21:41 UTC, arromeo commented on packages/client/src/shared-components/dialog/dialog-container.tsx
> +        {HeaderComponent && <HeaderComponent />}
Could we use a rendered prop instead of passing a component to be rendered inside this component?
```
  <BaseDialog header={<header />} />
```

2021-01-01 21:00 UTC, bert-bae commented on packages/client/src/shared-components/dialog/dialog-container.tsx
> +        {HeaderComponent && <HeaderComponent />}
updated

2021-01-01 21:01 UTC, bert-bae commented on packages/client/src/shared-components/dialog/dialog-container.tsx
> +        {HeaderComponent && <HeaderComponent />}
> I'm thinking this Storybook directory should be in the .gitignore? I thought I had setup and deleted all of the Storybook boilerplate. Was this generated by something?

As for the storybook directory, I haven't adjusted any of it

2021-01-02 01:02 UTC, arromeo approved these changes

2021-01-02 01:17 UTC, merged